대출 상담 등록 기능 테스트
테스트 진행 시 아래의 오류 발생
Could not initialize plugin: interface org.mockito.plugins.InstantiatorProvider2 (alternate: null)
...
Caused by: java.lang.NoClassDefFoundError: org/objenesis/ObjenesisStd

따라서, build.gradle에 objenesis 의존성 추가

했더니 테스트 ok